---
apiVersion: v1
kind: Service
metadata:
  name: camel-integration
  namespace: file-pipeline
  labels:
    app.kubernetes.io/name: camel-integration
    app.kubernetes.io/component: message-processor
    app.kubernetes.io/part-of: file-transfer-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
    prometheus.io/path: "/q/metrics"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: camel-integration
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: management
      port: 9000
      targetPort: management
      protocol: TCP
